name: "SurvivalEUPlugin"
main: "me.aggellos2001.survivaleuplugin.SurvivalEUPlugin"
version: "1.16.4-1"
author: "aggellos2001"
api-version: "1.16"
depend:
  - Vault
  - Essentials
  - LuckPerms
  - GriefPrevention
  - SkinsRestorer